# Generated by Django 3.0 on 2020-06-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('imgup', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
